

# This file was *autogenerated* from the file GaussSumTable.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_8p5 = RealNumber('8.5'); _sage_const_11 = Integer(11); _sage_const_0p5 = RealNumber('0.5'); _sage_const_0p95 = RealNumber('0.95'); _sage_const_14 = Integer(14); _sage_const_0p85 = RealNumber('0.85'); _sage_const_0p1 = RealNumber('0.1'); _sage_const_12 = Integer(12); _sage_const_0p05 = RealNumber('0.05'); _sage_const_3 = Integer(3)
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
from sage.all import GF, e, pi, I, latex

class GaussSumTable:
    def __init__(self, q, additive_character_generator, multiplicative_character_generator):
        self.q = q
        self.additive_character_generator = additive_character_generator
        self.multiplicative_character_generator = multiplicative_character_generator
        
        self.finite_field = GF(q**_sage_const_2 )
        self.generator = self.finite_field.gen()
        self.finite_field_elements = list(self.finite_field)
        self.finite_field_multiplicative_group = [x for x in self.finite_field_elements if x != _sage_const_0 ]
        
        self.table = [[_sage_const_0  for _ in range(q - _sage_const_1 )] for _ in range(q**_sage_const_2  - _sage_const_1 )]
        self.compute_gauss_sum_table()

    def compute_gauss_sum_table(self):
        for theta in range(self.q**_sage_const_2  - _sage_const_1 ):
            for alpha in range(self.q - _sage_const_1 ):
                self.table[theta][alpha] = self.compute_gauss_sum(theta, alpha)

    def compute_gauss_sum(self, theta, alpha):
        total = _sage_const_0 
        for x in self.finite_field_multiplicative_group:
            additive_character_value = self.additive_character_generator**self.trace(x)
            theta_character_value = self.multiplicative_character_generator**(theta * self.log(x))
            alpha_character_value = self.multiplicative_character_generator**(alpha * self.get_norm_log(x))
            total += additive_character_value * theta_character_value * alpha_character_value
        return total

    def get_norm_log(self, x):
        return (self.q + _sage_const_1 ) * self.log(x)

    def log(self, x):
        return x.log(self.generator) if x != _sage_const_0  else _sage_const_0   # Using the logarithm in finite fields

    def trace(self, x):
        return x.trace()  # Using the field trace function from GF(q^2) to GF(q)

def complex_gauss_sum_table(q):
    prime_power_result = q.is_prime_power(get_data=True)
    if prime_power_result[_sage_const_1 ] == _sage_const_0 :
        raise ValueError("Expected a prime power!")
    p = prime_power_result[_sage_const_0 ]
        
    return GaussSumTable(q, e**(_sage_const_2  * pi * I / p), e**(_sage_const_2  * pi * I / (q*q - _sage_const_1 )))

def save_gauss_sum_table_as_latex_pdf(table, filename="GaussSumTable_LaTeX.pdf"):
    """
    Saves the Gauss sum table in a structured LaTeX format inside a PDF.
    Each entry appears on a separate row and is sorted.
    """
    # Flatten the table into a single list and sort it
    sorted_entries = sorted([latex(entry) for row in table for entry in row])

    with PdfPages(filename) as pdf:
        fig, ax = plt.subplots(figsize=(_sage_const_8p5 , _sage_const_11 ))  # Letter-sized page
        ax.axis('off')  # Remove axes

        # Title
        ax.text(_sage_const_0p5 , _sage_const_0p95 , "Gauss Sum Table", fontsize=_sage_const_14 , ha='center')

        y_position = _sage_const_0p85   # Start position for the equations

        for entry in sorted_entries:
            latex_equation = r"$" + entry + r"$"  # Convert to LaTeX equation format
            
            ax.text(_sage_const_0p1 , y_position, latex_equation, fontsize=_sage_const_12 , ha='left', family='monospace')
            y_position -= _sage_const_0p05   # Move down for the next line
            
            if y_position < _sage_const_0p1 :  # Create a new page if out of space
                pdf.savefig(fig, bbox_inches='tight')
                plt.close(fig)
                fig, ax = plt.subplots(figsize=(_sage_const_8p5 , _sage_const_11 ))
                ax.axis('off')
                y_position = _sage_const_0p85   # Reset for new page
        
        pdf.savefig(fig, bbox_inches='tight')  # Save the final page
        plt.close(fig)
    
    print(f"Saved Gauss Sum Table as {filename}")

# Generate the Gauss Sum Table
gauss_sum_table_object = complex_gauss_sum_table(_sage_const_3 )
table_of_gauss_sum = gauss_sum_table_object.table

# Save as LaTeX-formatted PDF
save_gauss_sum_table_as_latex_pdf(table_of_gauss_sum)

